# Generated by Django 4.2.3 on 2023-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
