# Generated by Django 4.2.3 on 2023-07-22 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_category_post_categories"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Categories",
        ),
    ]
