# Generated by Django 4.2.3 on 2023-07-22 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_rename_category_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name_plural": "categories"},
        ),
    ]
